### ISSUE TITLE
Could not start firefox. Exit code: 127

### ISSUE THREAD

**Issue by imsatender** [symfony/panther#419]
Everytime I am getting below mentioned error while trying to execute the code inside docker, using the Dockerfile which is available on the project README

`2021-02-08 16:37:30::Exception Thrown::Could not start firefox. Exit code: 127 (Command not found). Error output: sh: 1: exec: /var/www/html/dyninno/phpcrawl/vendor/symfony/panther/src/ProcessManager/../../geckodriver-bin/geckodriver-linux64: not found

#0 /var/www/html/dyninno/phpcrawl/vendor/symfony/panther/src/ProcessManager/FirefoxManager.php(48): Symfony\Component\Panther\ProcessManager\FirefoxManager->waitUntilReady(Object(Symfony\Component\Process\Process), 'http://127.0.0....', 'firefox')
#1 /var/www/html/dyninno/phpcrawl/vendor/symfony/panther/src/Client.php(98): Symfony\Component\Panther\ProcessManager\FirefoxManager->start()
#2 /var/www/html/dyninno/phpcrawl/vendor/symfony/panther/src/Client.php(451): Symfony\Component\Panther\Client->start()
#3 /var/www/html/dyninno/phpcrawl/index.php(40): Symfony\Component\Panther\Client->manage()
#4 {main}
`

**Comment by imsatender** [comment]
Issue after composer update, I have older `composer.lock` content below, which is working fine and I think it is due to the `symphony/process` pkg

`{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
        "This file is @generated automatically"
    ],
    "content-hash": "3cc0f7e7274dd21b56ffac74a9b963a8",
    "packages": [
        {
            "name": "php-webdriver/webdriver",
            "version": "1.9.0",
            "source": {
                "type": "git",
                "url": "https://github.com/php-webdriver/php-webdriver.git",
                "reference": "e3633154554605274cc9d59837f55a7427d72003"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/php-webdriver/php-webdriver/zipball/e3633154554605274cc9d59837f55a7427d72003",
                "reference": "e3633154554605274cc9d59837f55a7427d72003",
                "shasum": ""
            },
            "require": {
                "ext-curl": "*",
                "ext-json": "*",
                "ext-zip": "*",
                "php": "^5.6 || ~7.0 || ^8.0",
                "symfony/polyfill-mbstring": "^1.12",
                "symfony/process": "^2.8 || ^3.1 || ^4.0 || ^5.0"
            },
            "replace": {
                "facebook/webdriver": "*"
            },
            "require-dev": {
                "friendsofphp/php-cs-fixer": "^2.0",
                "ondram/ci-detector": "^2.1 || ^3.5",
                "php-coveralls/php-coveralls": "^2.4",
                "php-mock/php-mock-phpunit": "^1.1 || ^2.0",
                "php-parallel-lint/php-parallel-lint": "^1.2",
                "phpunit/phpunit": "^5.7 || ^7 || ^8 || ^9",
                "squizlabs/php_codesniffer": "^3.5",
                "symfony/var-dumper": "^3.3 || ^4.0 || ^5.0"
            },
            "suggest": {
                "ext-SimpleXML": "For Firefox profile creation"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-main": "1.8.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Facebook\\WebDriver\\": "lib/"
                },
                "files": [
                    "lib/Exception/TimeoutException.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "description": "A PHP client for Selenium WebDriver. Previously facebook/webdriver.",
            "homepage": "https://github.com/php-webdriver/php-webdriver",
            "keywords": [
                "Chromedriver",
                "geckodriver",
                "php",
                "selenium",
                "webdriver"
            ],
            "time": "2020-11-19T15:21:05+00:00"
        },
        {
            "name": "psr/container",
            "version": "1.0.0",
            "source": {
                "type": "git",
                "url": "https://github.com/php-fig/container.git",
                "reference": "b7ce3b176482dbbc1245ebf52b181af44c2cf55f"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/php-fig/container/zipball/b7ce3b176482dbbc1245ebf52b181af44c2cf55f",
                "reference": "b7ce3b176482dbbc1245ebf52b181af44c2cf55f",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.0"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.0.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Psr\\Container\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "PHP-FIG",
                    "homepage": "http://www.php-fig.org/"
                }
            ],
            "description": "Common Container Interface (PHP FIG PSR-11)",
            "homepage": "https://github.com/php-fig/container",
            "keywords": [
                "PSR-11",
                "container",
                "container-interface",
                "container-interop",
                "psr"
            ],
            "time": "2017-02-14T16:28:37+00:00"
        },
        {
            "name": "psr/log",
            "version": "1.1.3",
            "source": {
                "type": "git",
                "url": "https://github.com/php-fig/log.git",
                "reference": "0f73288fd15629204f9d42b7055f72dacbe811fc"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/php-fig/log/zipball/0f73288fd15629204f9d42b7055f72dacbe811fc",
                "reference": "0f73288fd15629204f9d42b7055f72dacbe811fc",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.0"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.1.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Psr\\Log\\": "Psr/Log/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "PHP-FIG",
                    "homepage": "http://www.php-fig.org/"
                }
            ],
            "description": "Common interface for logging libraries",
            "homepage": "https://github.com/php-fig/log",
            "keywords": [
                "log",
                "psr",
                "psr-3"
            ],
            "time": "2020-03-23T09:12:05+00:00"
        },
        {
            "name": "symfony/browser-kit",
            "version": "v5.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/browser-kit.git",
                "reference": "4fc769a12282a12bc47f883f04f01ff3777e369b"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/browser-kit/zipball/4fc769a12282a12bc47f883f04f01ff3777e369b",
                "reference": "4fc769a12282a12bc47f883f04f01ff3777e369b",
                "shasum": ""
            },
            "require": {
                "php": ">=7.2.5",
                "symfony/dom-crawler": "^4.4|^5.0"
            },
            "require-dev": {
                "symfony/css-selector": "^4.4|^5.0",
                "symfony/http-client": "^4.4|^5.0",
                "symfony/mime": "^4.4|^5.0",
                "symfony/process": "^4.4|^5.0"
            },
            "suggest": {
                "symfony/process": ""
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Symfony\\Component\\BrowserKit\\": ""
                },
                "exclude-from-classmap": [
                    "/Tests/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Fabien Potencier",
                    "email": "fabien@symfony.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony BrowserKit Component",
            "homepage": "https://symfony.com",
            "time": "2020-11-14T11:04:29+00:00"
        },
        {
            "name": "symfony/dom-crawler",
            "version": "v5.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/dom-crawler.git",
                "reference": "0969122fe144dd8ab2e8c98c7e03eedc621b368c"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/dom-crawler/zipball/0969122fe144dd8ab2e8c98c7e03eedc621b368c",
                "reference": "0969122fe144dd8ab2e8c98c7e03eedc621b368c",
                "shasum": ""
            },
            "require": {
                "php": ">=7.2.5",
                "symfony/polyfill-ctype": "~1.8",
                "symfony/polyfill-mbstring": "~1.0",
                "symfony/polyfill-php80": "^1.15"
            },
            "conflict": {
                "masterminds/html5": "<2.6"
            },
            "require-dev": {
                "masterminds/html5": "^2.6",
                "symfony/css-selector": "^4.4|^5.0"
            },
            "suggest": {
                "symfony/css-selector": ""
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Symfony\\Component\\DomCrawler\\": ""
                },
                "exclude-from-classmap": [
                    "/Tests/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Fabien Potencier",
                    "email": "fabien@symfony.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony DomCrawler Component",
            "homepage": "https://symfony.com",
            "time": "2020-10-24T12:01:57+00:00"
        },
        {
            "name": "symfony/http-client",
            "version": "v5.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/http-client.git",
                "reference": "5b9fc5d85a6cec73832ff170ccd468d97dd082d9"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/http-client/zipball/5b9fc5d85a6cec73832ff170ccd468d97dd082d9",
                "reference": "5b9fc5d85a6cec73832ff170ccd468d97dd082d9",
                "shasum": ""
            },
            "require": {
                "php": ">=7.2.5",
                "psr/log": "^1.0",
                "symfony/http-client-contracts": "^2.2",
                "symfony/polyfill-php73": "^1.11",
                "symfony/polyfill-php80": "^1.15",
                "symfony/service-contracts": "^1.0|^2"
            },
            "provide": {
                "php-http/async-client-implementation": "*",
                "php-http/client-implementation": "*",
                "psr/http-client-implementation": "1.0",
                "symfony/http-client-implementation": "1.1"
            },
            "require-dev": {
                "amphp/amp": "^2.5",
                "amphp/http-client": "^4.2.1",
                "amphp/http-tunnel": "^1.0",
                "amphp/socket": "^1.1",
                "guzzlehttp/promises": "^1.3.1",
                "nyholm/psr7": "^1.0",
                "php-http/httplug": "^1.0|^2.0",
                "psr/http-client": "^1.0",
                "symfony/dependency-injection": "^4.4|^5.0",
                "symfony/http-kernel": "^4.4.13|^5.1.5",
                "symfony/process": "^4.4|^5.0",
                "symfony/stopwatch": "^4.4|^5.0"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Symfony\\Component\\HttpClient\\": ""
                },
                "exclude-from-classmap": [
                    "/Tests/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony HttpClient component",
            "homepage": "https://symfony.com",
            "time": "2020-11-28T13:45:20+00:00"
        },
        {
            "name": "symfony/http-client-contracts",
            "version": "v2.3.1",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/http-client-contracts.git",
                "reference": "41db680a15018f9c1d4b23516059633ce280ca33"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/http-client-contracts/zipball/41db680a15018f9c1d4b23516059633ce280ca33",
                "reference": "41db680a15018f9c1d4b23516059633ce280ca33",
                "shasum": ""
            },
            "require": {
                "php": ">=7.2.5"
            },
            "suggest": {
                "symfony/http-client-implementation": ""
            },
            "type": "library",
            "extra": {
                "branch-version": "2.3",
                "branch-alias": {
                    "dev-main": "2.3-dev"
                },
                "thanks": {
                    "name": "symfony/contracts",
                    "url": "https://github.com/symfony/contracts"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Contracts\\HttpClient\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Generic abstractions related to HTTP clients",
            "homepage": "https://symfony.com",
            "keywords": [
                "abstractions",
                "contracts",
                "decoupling",
                "interfaces",
                "interoperability",
                "standards"
            ],
            "time": "2020-10-14T17:08:19+00:00"
        },
        {
            "name": "symfony/panther",
            "version": "v0.8.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/panther.git",
                "reference": "04a6e5552e66080eb2549017e106b061090a6f56"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/panther/zipball/04a6e5552e66080eb2549017e106b061090a6f56",
                "reference": "04a6e5552e66080eb2549017e106b061090a6f56",
                "shasum": ""
            },
            "require": {
                "php": ">=7.1",
                "php-webdriver/webdriver": "^1.8.2",
                "symfony/browser-kit": "^4.4 || ^5.0",
                "symfony/dom-crawler": "^4.4 || ^5.0",
                "symfony/http-client": "^4.4 || ^5.0",
                "symfony/polyfill-php72": "^1.9",
                "symfony/process": "^4.4 || ^5.0"
            },
            "conflict": {
                "symfony/framework-bundle": ">=4.3 <4.3.4"
            },
            "require-dev": {
                "fabpot/goutte": "^3.2.3",
                "guzzlehttp/guzzle": "^6.3",
                "symfony/css-selector": "^4.4 || ^5.0",
                "symfony/framework-bundle": "^4.4 || ^5.0",
                "symfony/mime": "^4.4 || ^5.0",
                "symfony/phpunit-bridge": "dev-master"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.0.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Component\\Panther\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Kévin Dunglas",
                    "email": "dunglas@gmail.com",
                    "homepage": "https://dunglas.fr"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "A browser testing and web scraping library for PHP and Symfony.",
            "homepage": "https://dunglas.fr",
            "keywords": [
                "e2e",
                "scraping",
                "selenium",
                "symfony",
                "testing",
                "webdriver"
            ],
            "time": "2020-10-03T09:22:56+00:00"
        },
        {
            "name": "symfony/polyfill-ctype",
            "version": "v1.20.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/polyfill-ctype.git",
                "reference": "f4ba089a5b6366e453971d3aad5fe8e897b37f41"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/polyfill-ctype/zipball/f4ba089a5b6366e453971d3aad5fe8e897b37f41",
                "reference": "f4ba089a5b6366e453971d3aad5fe8e897b37f41",
                "shasum": ""
            },
            "require": {
                "php": ">=7.1"
            },
            "suggest": {
                "ext-ctype": "For best performance"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-main": "1.20-dev"
                },
                "thanks": {
                    "name": "symfony/polyfill",
                    "url": "https://github.com/symfony/polyfill"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Polyfill\\Ctype\\": ""
                },
                "files": [
                    "bootstrap.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Gert de Pagter",
                    "email": "BackEndTea@gmail.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony polyfill for ctype functions",
            "homepage": "https://symfony.com",
            "keywords": [
                "compatibility",
                "ctype",
                "polyfill",
                "portable"
            ],
            "time": "2020-10-23T14:02:19+00:00"
        },
        {
            "name": "symfony/polyfill-mbstring",
            "version": "v1.20.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/polyfill-mbstring.git",
                "reference": "39d483bdf39be819deabf04ec872eb0b2410b531"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/39d483bdf39be819deabf04ec872eb0b2410b531",
                "reference": "39d483bdf39be819deabf04ec872eb0b2410b531",
                "shasum": ""
            },
            "require": {
                "php": ">=7.1"
            },
            "suggest": {
                "ext-mbstring": "For best performance"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-main": "1.20-dev"
                },
                "thanks": {
                    "name": "symfony/polyfill",
                    "url": "https://github.com/symfony/polyfill"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Polyfill\\Mbstring\\": ""
                },
                "files": [
                    "bootstrap.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony polyfill for the Mbstring extension",
            "homepage": "https://symfony.com",
            "keywords": [
                "compatibility",
                "mbstring",
                "polyfill",
                "portable",
                "shim"
            ],
            "time": "2020-10-23T14:02:19+00:00"
        },
        {
            "name": "symfony/polyfill-php72",
            "version": "v1.20.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/polyfill-php72.git",
                "reference": "cede45fcdfabdd6043b3592e83678e42ec69e930"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/polyfill-php72/zipball/cede45fcdfabdd6043b3592e83678e42ec69e930",
                "reference": "cede45fcdfabdd6043b3592e83678e42ec69e930",
                "shasum": ""
            },
            "require": {
                "php": ">=7.1"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-main": "1.20-dev"
                },
                "thanks": {
                    "name": "symfony/polyfill",
                    "url": "https://github.com/symfony/polyfill"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Polyfill\\Php72\\": ""
                },
                "files": [
                    "bootstrap.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions",
            "homepage": "https://symfony.com",
            "keywords": [
                "compatibility",
                "polyfill",
                "portable",
                "shim"
            ],
            "time": "2020-10-23T14:02:19+00:00"
        },
        {
            "name": "symfony/polyfill-php73",
            "version": "v1.20.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/polyfill-php73.git",
                "reference": "8ff431c517be11c78c48a39a66d37431e26a6bed"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/polyfill-php73/zipball/8ff431c517be11c78c48a39a66d37431e26a6bed",
                "reference": "8ff431c517be11c78c48a39a66d37431e26a6bed",
                "shasum": ""
            },
            "require": {
                "php": ">=7.1"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-main": "1.20-dev"
                },
                "thanks": {
                    "name": "symfony/polyfill",
                    "url": "https://github.com/symfony/polyfill"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Polyfill\\Php73\\": ""
                },
                "files": [
                    "bootstrap.php"
                ],
                "classmap": [
                    "Resources/stubs"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions",
            "homepage": "https://symfony.com",
            "keywords": [
                "compatibility",
                "polyfill",
                "portable",
                "shim"
            ],
            "time": "2020-10-23T14:02:19+00:00"
        },
        {
            "name": "symfony/polyfill-php80",
            "version": "v1.20.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/polyfill-php80.git",
                "reference": "e70aa8b064c5b72d3df2abd5ab1e90464ad009de"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/polyfill-php80/zipball/e70aa8b064c5b72d3df2abd5ab1e90464ad009de",
                "reference": "e70aa8b064c5b72d3df2abd5ab1e90464ad009de",
                "shasum": ""
            },
            "require": {
                "php": ">=7.1"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-main": "1.20-dev"
                },
                "thanks": {
                    "name": "symfony/polyfill",
                    "url": "https://github.com/symfony/polyfill"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Polyfill\\Php80\\": ""
                },
                "files": [
                    "bootstrap.php"
                ],
                "classmap": [
                    "Resources/stubs"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Ion Bazan",
                    "email": "ion.bazan@gmail.com"
                },
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions",
            "homepage": "https://symfony.com",
            "keywords": [
                "compatibility",
                "polyfill",
                "portable",
                "shim"
            ],
            "time": "2020-10-23T14:02:19+00:00"
        },
        {
            "name": "symfony/process",
            "version": "v5.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/process.git",
                "reference": "240e74140d4d956265048f3025c0aecbbc302d54"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/process/zipball/240e74140d4d956265048f3025c0aecbbc302d54",
                "reference": "240e74140d4d956265048f3025c0aecbbc302d54",
                "shasum": ""
            },
            "require": {
                "php": ">=7.2.5",
                "symfony/polyfill-php80": "^1.15"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Symfony\\Component\\Process\\": ""
                },
                "exclude-from-classmap": [
                    "/Tests/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Fabien Potencier",
                    "email": "fabien@symfony.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Symfony Process Component",
            "homepage": "https://symfony.com",
            "time": "2020-11-02T15:47:15+00:00"
        },
        {
            "name": "symfony/service-contracts",
            "version": "v2.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/service-contracts.git",
                "reference": "d15da7ba4957ffb8f1747218be9e1a121fd298a1"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/service-contracts/zipball/d15da7ba4957ffb8f1747218be9e1a121fd298a1",
                "reference": "d15da7ba4957ffb8f1747218be9e1a121fd298a1",
                "shasum": ""
            },
            "require": {
                "php": ">=7.2.5",
                "psr/container": "^1.0"
            },
            "suggest": {
                "symfony/service-implementation": ""
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "2.2-dev"
                },
                "thanks": {
                    "name": "symfony/contracts",
                    "url": "https://github.com/symfony/contracts"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Contracts\\Service\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "Generic abstractions related to writing services",
            "homepage": "https://symfony.com",
            "keywords": [
                "abstractions",
                "contracts",
                "decoupling",
                "interfaces",
                "interoperability",
                "standards"
            ],
            "time": "2020-09-07T11:33:47+00:00"
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": []
}
`

**Comment by dbrekelmans** [comment]
From your error message: `/var/www/html/dyninno/phpcrawl/vendor/symfony/panther/src/ProcessManager/../../geckodriver-bin/geckodriver-linux64: not found`

The file should be there in panther 0.8 (it has been removed since 0.9).
Either find out why the file is might be missing (maybe incorrect relative path?) or upgrade to 0.9 or 1.0 and follow the readme to install the driver ;)
