### ISSUE TITLE
Display the testing window if run in docker

### ISSUE THREAD

**Issue by versh23** [symfony/panther#97]
is it possible to run tests with `ENV PANTHER_NO_HEADLESS 1` in docker ?

now i get error 

```

Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"binary":"","args":["--no-sandbox"]}}}

Operation timed out after 30001 milliseconds with 0 bytes received in /app/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:292
Stack trace:
#0 /app/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 /app/vendor/symfony/panther/src/ProcessManager/ChromeManager.php(59): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://127.0.0....', Object(Facebook\WebDriver\Remote\DesiredCapabilities))
#2 /app/vendor/symfony/panther/src/Client.php(74): Symfony\Component\Panther\ProcessManager\ChromeManager->start()
#3 /app/vendor/symfony/panther/src/Client.php(245): Symfony\Component\Panther\Client->start()
#4 /app/vendor/symfony/panther/src/Client.ph in /app/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php on line 292

```

i tried to start chromedriver on host machine, and share 9515 port - but same error

**Comment by dunglas** [comment]
It's possible, but more complicated. You'll have to configure a proper install of X, and configure the sharing with the host.
See https://medium.com/dot-debug/running-chrome-in-a-docker-container-a55e7f4da4a8

**Comment by versh23** [comment]
too complicated :) i think that panther use a WebDriver that connect to the chromedriver on host machine

- Panther in docker
- chromedriver + chrome app in host 

is it realy need a X ?
